const jp = require('jsonpath')

const str = '{ "store": { "book": [ { "category": "reference", "author": "Nigel Rees", "title": "Sayings of the Century", "price": 8.95 }, { "category": "fiction", "author": "Evelyn Waugh", "title": "Sword of Honour", "price": 12.99 }, { "category": "fiction", "author": "Herman Melville", "title": "Moby Dick", "isbn": "0-553-21311-3", "price": 8.99 }, { "category": "fiction", "author": "J. R. R. Tolkien", "title": "The Lord of the Rings", "isbn": "0-395-19395-8", "price": 22.99 } ], "bicycle": { "color": "red", "price": 19.95 } } }'
const RAW_JS_1 = '{ "data": { "card_information": [ { "confidence_score": 1, "confidence_verdict": "SURE", "digit_confidence_scores": [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ], "field": "id", "value": "0123456789" }, { "confidence_score": 1, "confidence_verdict": "SURE", "field": "name", "value": "PHÙNG THỊ MAI LINH" }, { "confidence_score": 1, "confidence_verdict": "SURE", "field": "dob", "value": "01/01/1998" }, { "confidence_score": 1, "confidence_verdict": "", "field": "native_place", "value": "XÃ PHÚ LƯƠNG, HUYỆN SƠN DƯƠNG, TUYÊN QUANG" }, { "confidence_score": 1, "confidence_verdict": "SURE", "field": "address", "value": "KHU 7, XÃ PHÚ MỸ, PHÙ NINH, PHÚ THỌ" }, { "confidence_score": 1, "confidence_verdict": "", "field": "address_level_1_(city)", "value": "PHÚ THỌ" }, { "confidence_score": 1, "confidence_verdict": "", "field": "address_level_1_(city)_code", "value": "25" }, { "confidence_score": 1, "confidence_verdict": "", "field": "address_level_2_(district)", "value": "PHÙ NINH" }, { "confidence_score": 1, "confidence_verdict": "", "field": "address_level_2_(district)_code", "value": "233" }, { "confidence_score": 1, "confidence_verdict": "", "field": "address_level_3_(ward)", "value": "PHÚ MỸ" }, { "confidence_score": 1, "confidence_verdict": "", "field": "address_level_3_(ward)_code", "value": "08233" }, { "confidence_score": 1, "confidence_verdict": "", "field": "address_level_4", "value": "KHU 7" }, { "confidence_score": 1, "confidence_verdict": "", "field": "first_name", "value": "LINH" }, { "confidence_score": 1, "confidence_verdict": "", "field": "last_name", "value": "PHÙNG" }, { "confidence_score": 1, "confidence_verdict": "", "field": "middle_name", "value": "THỊ MAI" }, { "confidence_score": 1, "confidence_verdict": "SURE", "field": "issue_date", "value": "16/03/2015" }, { "confidence_score": 1, "confidence_verdict": "", "field": "issue_place", "value": "GIÁM ĐỐC CA PHÚ THỌ" }, { "field": "card_type", "value": "vn.cmnd_old" }, { "field": "card_label", "value": "vn.cmnd_old.front" } ], "index_faces_id_card": { "status": "success" }, "index_faces_portrait": { "status": "success" }, "input_params": { "card_type": "vn.national_id", "image1_id": "61903255-5069-4521-b8c5-a04d4b73a9cd", "image2_id": "a6ff3bf6-a95b-418d-a17d-32be486d2a85", "selfies": [ "5fc7a98c-f461-4bee-a19f-608c63481c00" ] }, "liveness_check": { "is_live": true, "score": 1 }, "request_id": "621ab9db-bf4d-429f-bd1a-25e7bd3203df", "status": "success", "transaction_id": "fd8677e0-78d3-444e-82ef-3f9a1866d6f1" } }'

const obj = JSON.parse(str)
let authors = jp.query(obj, '$..author')
// console.log(authors)

const obj1 = JSON.parse(RAW_JS_1)
let cardInformation = jp.query(obj1, '$.data.card_information[?(@.field==\'id\')].value')
console.log(cardInformation)